feat: 일기장 관련 엔티티 구현
taehyeon-brothers/writeln-backend pull request #3
Opened 2024-09-21 08:47 UTC by kth990303

## 개요
- 일기장 관련 엔티티를 구현했습니다. 그 외 계층은 껍데기만 구현했어요.
- 일기장에는 여러 태그가 붙을 수 있고, 하나의 태그는 여러 일기장에 들어갈 수 있을 것 같은데요. 그래서 N:M 구조일 것 같아요. 양방향 vs 단방향 고민했다가 일단 단방향으로만 구현했습니다.

## 메인 리뷰어 지정 및 Due Date
- 메인 리뷰어 : @pjy1368  , Due Date : 2024-09-25(수) (급하진 않다고 생각함)

## 리뷰 시 참고 사항
- 리뷰어에게 의견이 필요하거나, 리뷰어가 중점적으로 보면 좋을 부분을 나열해주세요.
    - Diary-Tag 간 관계

## TODO
- 테스트 코드 (필수적)

## References
없음.

## 체크리스트
- [x] PR 제목을 명령형으로 작성했습니다.
- [x] 리뷰 리퀘스트 전에 셀프 리뷰를 진행했습니다.
- [x] 변경사항에 대한 테스트코드를 추가했습니다. 또는, 테스트코드가 필요없는 이유가 있습니다. **(별도 서브모듈에 User 테스트코드 구현되면 따르겠습니다.)**

2024-09-21 10:02 UTC, blue000927 requested changes

2024-09-21 10:02 UTC, blue000927 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    var userId: Long,
User 연관 관계 매핑은 안할 예정이신가요?

2024-09-21 10:02 UTC, blue000927 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Tag.kt
> +    var diaryId: Long = 0,
ditto (연관 관계 여부)

2024-09-21 10:02 UTC, blue000927 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    val id: Long = 0,
일단 id는 auto-increment로 두긴했는데, 태현님 팀에서는 어떤 식으로 PK 값 설정하나요?

2024-09-21 10:02 UTC, blue000927 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    var content: String
content는 non-null이어야 하지 않을지??

2024-09-21 10:02 UTC, blue000927 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Tag.kt
> +    var content: String
content보다는 name이 적합하지 않을지? (태그 이름 느낌으로)
또한, content든 name이든 non-nullable이어야할 것 같아요.

2024-09-21 10:13 UTC, kth990303 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    var content: String
냉무 같은 케이스땜에 일단 nullable 하게 했는데, nonnull도 좋은거같아요

2024-09-21 10:13 UTC, kth990303 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    val id: Long = 0,
auto increment로 합니다

2024-09-21 10:14 UTC, kth990303 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    var userId: Long,
아이디만 갖고있는 방식을 생각했는데요, manytoone 추가하는순간 외래키가 생겨버려서요

 추가되는게 좋을까요?

2024-09-21 10:14 UTC, kth990303 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Tag.kt
> +    var content: String
이름 좀 고민됐는데 name 좋네요 수정할게요!

2024-09-22 04:00 UTC, blue000927 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    var userId: Long,
`@JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(ConstraintMode.NO_CONSTRAINT)` 설정하면 외래 키 없이 연관 관계 매핑 가능해요.
근데 연관 관계 매핑하는건 좀 취향인 것 같아서 자유롭게 해도 될듯?

2024-09-22 04:00 UTC, blue000927 approved these changes

2024-09-22 04:29 UTC, kth990303 commented on src/main/kotlin/taehyeon/brothers/writeln_backend/domain/Diary.kt
> +    var userId: Long,
오, 이렇게 써본적이 없어서 몰랐네요. 이번 기회에 써보죠 ㅎㅎ 제가 적용하고 낼쯤 머지할게요~~

2024-10-16 12:38 UTC, merged